runtime: custom
vm: true
service: jetty-runtime-perf-app
resources:
  cpu: ${resources.cpu}
  memory_gb: ${resources.memory_gb}
  disk_size_gb: ${resources.disk_size_gb}
automatic_scaling:
  min_num_instances: ${automatic_scaling.min_num_instances}
  max_num_instances: ${automatic_scaling.max_num_instances}
handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always
health_check:
  enable_health_check: False
