runtime: custom
vm: true
service: jetty-runtime-perf-runner
resources:
  cpu: 2
  memory_gb: 8
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: ${runner.instances}
  max_num_instances: ${runner.instances}
handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always
health_check:
  enable_health_check: False
